server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/feedback/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
        - id: prescription-service
          uri: lb://prescription-service
          predicates:
            - Path=/api/prescriptions/**
    loadbalancer:
      ribbon:
        enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - ${FRONTEND_URL:https://your-frontend-url.vercel.app}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
